export global ColWidth {
    in-out property <length> pid: 50px;
    in-out property <length> ppid: 50px;
    in-out property <length> state: 80px;
    in-out property <length> user: 60px;
    in-out property <length> start-time: 100px;
    in-out property <length> command: 200px;
    out property <length> all-except-name: pid + ppid + state + user + start-time + command;
}

export struct ProcessProps {
    name: string,
    pid: int,
    ppid: int,
    state: string,
    user: string,
    user_id: int,
    start_time: string,
    command: string,
}

export component Process {
    in property <ProcessProps> process;

    HorizontalLayout {
        width: parent.width;

        Text {
            text: process.name;
            width: parent.width > 0 ? parent.width - ColWidth.all-except-name : 0px;
        }

        Text {
            text: process.pid;
            width: ColWidth.pid;
        }

        Text {
            text: process.ppid;
            width: ColWidth.ppid;
        }

        Text {
            text: process.state;
            width: ColWidth.state;
        }

        Text {
            text: process.user;
            width: ColWidth.user;
        }

        Text {
            text: process.start_time;
            width: ColWidth.start-time;
        }

        Text {
            text: process.command;
            width: ColWidth.command;
        }
    }
}
