import "./IosevkaNerdFont-Regular.ttf";
import { StandardTableView } from "std-widgets.slint";

export global AppWindowState {
    in-out property <[[StandardListViewItem]]> procs: [];
}

export component AppWindow inherits Window {
    callback row-pointer-event(int, PointerEvent, Point);
    callback sort-ascending(int);
    callback sort-descending(int);

    title: "Task Manager";
    preferred-width: 800px;
    preferred-height: 600px;
    default-font-family: "Iosevka NF";

    StandardTableView {
        width: parent.width;
        height: parent.height;
        row-pointer-event(row, event, position) => {
            root.row-pointer-event(row, event, position);
        }
        sort-ascending(column) => {
            root.sort-ascending(column);
        }
        sort-descending(column) => {
            root.sort-descending(column);
        }

        columns: [
            { title: "Name" },
            { title: "ID" },
            { title: "CPU" },
            { title: "Memory" },
            { title: "PPID" },
            { title: "State" },
            { title: "Start Time" },
            { title: "User" },
            { title: "Command" }
        ];
        rows: AppWindowState.procs;
    }
}
